# Generated by Django 4.2.3 on 2024-07-08 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+251?1?\\d{9,15}$'), django.core.validators.MaxLengthValidator])),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='N', max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
